spring.application.name=jogos_internos

# =================================================
#      CONFIGURAÇÃO DO BANCO DE DADOS POSTGRESQL
# =================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_jogos_internos_v2
spring.datasource.username=postgres
spring.datasource.password=2003

# =================================================
#      CONFIGURAÇÃO DO JPA/HIBERNATE
# =================================================
# 'validate' checa se as tabelas do banco correspondem às suas classes Java. Ótimo para segurança.
spring.jpa.hibernate.ddl-auto=validate

# Mostra no console o SQL que está sendo executado. Ótimo para debug.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
